###

POST http://localhost:3000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "toransoverlook.net",
  "avatar": "torrance.png",
  "name": "Jack",
  "password": "shining",
  "type": "Pro"
}

###

POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}

###
