###

POST http://localhost:3000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "111@overlook.net",
  "avatar": "torrance.png",
  "name": "Jack",
  "password": "shining",
  "type": "Pro"
}

###

POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "111@overlook.net",
  "password": "shining"
}

###

GET http://localhost:3000/users/checkAuthenticate HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IjExMUBvdmVybG9vay5uZXQiLCJuYW1lIjoiSmFjayIsImlkIjoiNjc3MjQzNjc4ZTM0ZDFlNDRhMDAxMDk5IiwiaWF0IjoxNzM1NTQxNjY3LCJleHAiOjE3MzU3MTQ0Njd9.U3sIPZISWUUIGxkL01jGNlXvfgWWFr0f54FzxP5zyN0

###

GET http://localhost:3000/users/getFavorites HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IjExMUBvdmVybG9vay5uZXQiLCJuYW1lIjoiSmFjayIsImlkIjoiNjc3MjQzNjc4ZTM0ZDFlNDRhMDAxMDk5IiwiaWF0IjoxNzM1NTQxNjY3LCJleHAiOjE3MzU3MTQ0Njd9.U3sIPZISWUUIGxkL01jGNlXvfgWWFr0f54FzxP5zyN0

###
